/**
 * The series as they run on the YouTube channel, with their real episode lists.
 *
 * GENERATED by RF101-YT/automation/site/build_channel_series.py — edit that script, not this file.
 * `done` marks an episode that is published; `episodeCount` is the number published and is
 * left out where nothing is live yet.
 */
import type { Series } from "./types";

export const channelSeries: Series[] = [
  {
    "slug": "circuit-intuitions",
    "index": 12,
    "kind": "channel",
    "title": "Circuit Intuitions",
    "short": "One circuit idea per Short",
    "description": "One circuit idea per Short: Thévenin shortcuts, charge sharing, op-amp limits, memory cells. Each starts from a claim that sounds wrong and ends with the computed reason it is right.",
    "domains": [
      "Electronics"
    ],
    "level": "Intermediate",
    "image": "/images/series/circuit-intuitions.jpg",
    "topics": [
      {
        "title": "Looking into a Node",
        "done": true
      },
      {
        "title": "Looking Into Two Nodes",
        "done": true
      },
      {
        "title": "Miller's Approximation",
        "done": true
      },
      {
        "title": "The Electrical Length of a Wire",
        "done": true
      },
      {
        "title": "Source Degeneration",
        "done": true
      },
      {
        "title": "Capacitor as a Resistor",
        "done": true
      },
      {
        "title": "Why Sinusoids",
        "done": true
      },
      {
        "title": "Undo the Wire",
        "done": true
      },
      {
        "title": "Undo the Resistor",
        "done": true
      },
      {
        "title": "Turn the Knob",
        "done": true
      },
      {
        "title": "AC Coupling and Baseline Wander",
        "done": true
      },
      {
        "title": "Bandwidth Extension",
        "done": true
      },
      {
        "title": "Thévenin and Norton, Part 1",
        "done": true
      },
      {
        "title": "Voltage Follower, Part 1",
        "done": true
      },
      {
        "title": "Negative Resistance",
        "done": true
      },
      {
        "title": "Tellegen's Theorem",
        "done": true
      },
      {
        "title": "Random Walk in a Ring",
        "done": true
      },
      {
        "title": "Chopper Amplifier",
        "done": true
      },
      {
        "title": "Voltage Follower, Part II: the flip",
        "done": true
      },
      {
        "title": "Voltage Follower, Part II: two stages in disguise",
        "done": true
      },
      {
        "title": "Voltage Follower, Part II: wider, then steeper",
        "done": true
      },
      {
        "title": "Thévenin and Norton, Part 2: you could tell by touching it",
        "done": true
      },
      {
        "title": "Source transformation",
        "done": true
      },
      {
        "title": "Thévenin and Norton, Part 2: which form to pick",
        "done": true
      },
      {
        "title": "The source follower is a source transformation",
        "done": true
      },
      {
        "title": "An RC circuit does not average",
        "done": true
      },
      {
        "title": "Charging a capacitor always wastes half",
        "done": true
      },
      {
        "title": "A resistive divider is only as efficient as its ratio",
        "done": true
      },
      {
        "title": "Why your source follower stops following",
        "done": true
      },
      {
        "title": "Why your voltage follower is fast up and slow down",
        "done": true
      },
      {
        "title": "You found the voltage. Now you can't trust the resistance.",
        "done": true
      },
      {
        "title": "Close the switch. Half the energy is gone. Where did it go?",
        "done": true
      },
      {
        "title": "Zero resistance. Half the energy still vanishes."
      },
      {
        "title": "This amplifier wants ZERO input resistance. Why?"
      },
      {
        "title": "How do you cancel an error nobody measured?"
      },
      {
        "title": "This resistor is making noise. Nothing is connected."
      },
      {
        "title": "The noise on a capacitor ignores the resistor. Why?"
      },
      {
        "title": "Copy your amplifier once. Distortion drops from 13% to 5%. Why?"
      },
      {
        "title": "One resistor took distortion from 5% to 0.2%. What did it cost?"
      },
      {
        "title": "Every time your laptop reads its memory, it destroys it"
      }
    ],
    "episodeCount": 32
  },
  {
    "slug": "pcb-myths",
    "index": 13,
    "kind": "channel",
    "title": "PCB Myths",
    "short": "Board folklore, tested",
    "description": "PCB folklore, tested. Trace width, return current, split ground planes, ferrite beads: each myth is checked against a computed model rather than an opinion.",
    "domains": [
      "PCB"
    ],
    "level": "Intermediate",
    "image": "/images/series/pcb-myths.jpg",
    "topics": [
      {
        "title": "Your 90° corner is fine",
        "done": true
      },
      {
        "title": "1000× the capacitance, same noise",
        "done": true
      },
      {
        "title": "Stop using three capacitor values",
        "done": true
      },
      {
        "title": "How much current can a 6 mil PCB trace carry?",
        "done": true
      },
      {
        "title": "Why every copper square has the same resistance",
        "done": true
      },
      {
        "title": "Where does return current actually flow?",
        "done": true
      },
      {
        "title": "Why your oscilloscope shows the wrong rise time",
        "done": true
      },
      {
        "title": "Why your function generator shows double the voltage",
        "done": true
      },
      {
        "title": "Silver traces won't make your signals faster",
        "done": true
      },
      {
        "title": "Return current comes back instantly — even from an open cable",
        "done": true
      },
      {
        "title": "Don't split your ground plane",
        "done": true
      },
      {
        "title": "Copper pour makes crosstalk worse",
        "done": true
      },
      {
        "title": "This jumper wire is a 160 nH inductor",
        "done": true
      },
      {
        "title": "Your Arduino board doesn't need 50 Ω traces",
        "done": true
      },
      {
        "title": "Your 4-layer board doesn't need a power plane"
      },
      {
        "title": "Never share a ground via"
      },
      {
        "title": "A ferrite bead on every power pin? It can cost you half a volt"
      }
    ],
    "episodeCount": 14
  },
  {
    "slug": "interview-solved",
    "index": 14,
    "kind": "channel",
    "title": "Interview Solved",
    "short": "Placement questions, worked",
    "description": "Interview and placement questions in digital and VLSI design, solved step by step with computed schematics and truth tables.",
    "domains": [
      "Semiconductor",
      "Electronics"
    ],
    "level": "Intermediate",
    "image": "/images/series/interview-solved.jpg",
    "topics": [
      {
        "title": "What logic function is this CMOS circuit?",
        "done": true
      },
      {
        "title": "Every option is wrong. Can you find F? (VLSI interview)",
        "done": true
      },
      {
        "title": "One label is lying. Can you spot it? (VLSI interview)",
        "done": true
      },
      {
        "title": "Same transistors, same gates. Why do X and Y differ?",
        "done": true
      },
      {
        "title": "Six transistors, one input. What does it do?",
        "done": true
      },
      {
        "title": "Z is 1. One clock. What are S and Z?",
        "done": true
      },
      {
        "title": "Build a JK from a D flip-flop. One wire decides.",
        "done": true
      },
      {
        "title": "This is a flip-flop in disguise. Which one?",
        "done": true
      },
      {
        "title": "One inverter on the clock doubles the period.",
        "done": true
      },
      {
        "title": "One expression, five inputs. How many transistors in static CMOS?"
      }
    ],
    "episodeCount": 9
  },
  {
    "slug": "signals-101",
    "index": 15,
    "kind": "channel",
    "title": "Signals 101",
    "short": "Signals in under a minute",
    "description": "Signals and systems in under a minute each: periodicity, harmonics, sampling, spectra. Every waveform on screen is computed, not sketched.",
    "domains": [
      "Electronics"
    ],
    "level": "Beginner",
    "image": "/images/series/signals-101.jpg",
    "topics": [
      {
        "title": "Add two sine waves. It never repeats.",
        "done": true
      },
      {
        "title": "Your computer thinks 11 Hz is 1 Hz"
      },
      {
        "title": "Sample at exactly Nyquist and this sine wave vanishes. Why?"
      },
      {
        "title": "One sine wave carries 81% of a square wave. Guess before you watch."
      },
      {
        "title": "A square wave has no 2nd harmonic. It's not because it's odd."
      },
      {
        "title": "This signal has no 4th harmonic. Guess why before you watch."
      }
    ],
    "episodeCount": 1
  },
  {
    "slug": "rf-101-shorts",
    "index": 16,
    "kind": "channel",
    "title": "RF 101 Shorts",
    "short": "RF, one surprise at a time",
    "description": "RF from the first surprise: one wire, two voltages. Wavelength, reflections, standing waves and VSWR, with every graph recomputed from the equations.",
    "domains": [
      "RF"
    ],
    "level": "Intermediate",
    "image": "/images/series/rf-101-shorts.jpg",
    "topics": [
      {
        "title": "Same wire, two voltages. Can you see why? (10 GHz)",
        "done": true
      },
      {
        "title": "10 GHz gets less than 1 micron into copper. Guess how deep?"
      },
      {
        "title": "Short one end of a cable. The other end looks open?"
      },
      {
        "title": "Hang 200 Ω on a cable. The other end reads 12.5 Ω?"
      },
      {
        "title": "One strip of copper turns 100 Ω into 50 Ω. 75 Ω or 70.7 Ω?"
      },
      {
        "title": "20 dB of return loss = 1 % of your power back. 10 dB or 20 dB?"
      },
      {
        "title": "Mismatch a line and the wave stops travelling. That's VSWR"
      }
    ],
    "episodeCount": 1
  },
  {
    "slug": "art-of-electronics",
    "index": 17,
    "kind": "channel",
    "title": "Electronics 101: The Art of Electronics",
    "short": "Classic ideas, recomputed",
    "description": "Worked ideas in the spirit of the classic electronics text, one per Short, with every figure recomputed. Independent: not affiliated with the book's authors or publisher.",
    "domains": [
      "Electronics"
    ],
    "level": "Beginner",
    "image": "/images/series/art-of-electronics.jpg",
    "topics": [
      {
        "title": "One cable for a whole city loses it all in 26 feet. Where did the power go?",
        "done": true
      },
      {
        "title": "Both filters say 1 MHz. One barely filters. 20 dB or 140 dB?"
      },
      {
        "title": "β says 940 mA. The lamp says 100. Who wins? (GATE trap)"
      }
    ],
    "episodeCount": 1
  },
  {
    "slug": "carrier-wave",
    "index": 18,
    "kind": "channel",
    "title": "Carrier Wave",
    "short": "Communication systems",
    "description": "Communication systems one idea at a time: AM, FM, filters, mixers and the superheterodyne receiver. Follows the GATE communications syllabus.",
    "domains": [
      "RF",
      "Electronics"
    ],
    "level": "Intermediate",
    "image": "/images/series/carrier-wave.jpg",
    "topics": [
      {
        "title": "Your voice would need a 3 km antenna. Why doesn't it?"
      },
      {
        "title": "AM wastes 2/3 of its power. Why is it still on air?"
      },
      {
        "title": "Past 100% AM, your voice plays upside down."
      },
      {
        "title": "The capacitor in every AM radio has two jobs that fight."
      },
      {
        "title": "A perfect radio goes silent. The only fault is 90°."
      },
      {
        "title": "100 Hz off and everyone sounds like a duck. Why?"
      },
      {
        "title": "This radio filter can't be built. So they built two."
      },
      {
        "title": "Your radio can hear a station you never tuned."
      },
      {
        "title": "One choice in every radio avoids a 181:1 capacitor."
      }
    ]
  },
  {
    "slug": "antenna-fundamentals",
    "index": 19,
    "kind": "channel",
    "title": "Antenna Fundamentals 101",
    "short": "Antenna theory from zero",
    "description": "Antenna theory from the ground up: why a current radiates, what isotropic really means, and how directivity differs from gain.",
    "domains": [
      "Antenna",
      "RF"
    ],
    "level": "Beginner",
    "image": "/images/series/antenna-fundamentals.jpg",
    "topics": [
      {
        "title": "A steady current radiates nothing. So what makes a radio wave?"
      },
      {
        "title": "Every antenna gain is measured against an antenna that can't exist"
      }
    ]
  },
  {
    "slug": "antennas-in-the-wild",
    "index": 20,
    "kind": "channel",
    "title": "Antennas in the Wild",
    "short": "Antennas in real products",
    "description": "Antennas inside real products: phones, circuit boards, wearables. Why the same antenna behaves differently once it leaves the textbook.",
    "domains": [
      "Antenna"
    ],
    "level": "Intermediate",
    "image": "/images/series/antennas-in-the-wild.jpg",
    "topics": [
      {
        "title": "How you hold your phone can cut its signal by 84%"
      },
      {
        "title": "Print a phone antenna on a circuit board and it shrinks by half"
      }
    ]
  },
  {
    "slug": "gate-solved",
    "index": 21,
    "kind": "channel",
    "title": "GATE Solved",
    "short": "One question, one video",
    "description": "GATE questions solved one at a time: the circuit redrawn, every step computed and the waveform shown, never just the arithmetic.",
    "domains": [
      "Electronics"
    ],
    "level": "Intermediate",
    "image": "/images/series/gate-solved.jpg",
    "topics": [
      {
        "title": "GATE 2026 EC Q.65: two diodes, and the answer is not six"
      },
      {
        "title": "The cell is upside down — GATE 2025 EC Q.61"
      },
      {
        "title": "GATE 2026 — one switch closes. What happens to the output?"
      }
    ]
  },
  {
    "slug": "radar-101",
    "index": 22,
    "kind": "channel",
    "title": "Radar 101",
    "short": "How radar measures",
    "description": "How a radar measures range, angle and speed, one idea per Short: time of flight, monopulse, harmonic radar.",
    "domains": [
      "RF"
    ],
    "level": "Intermediate",
    "image": "/images/series/radar-101.jpg",
    "topics": [
      {
        "title": "This radar only sees electronics",
        "done": true
      },
      {
        "title": "One radar pulse gives the exact angle. How?"
      },
      {
        "title": "The echo is back in 1 microsecond. How far is the target?"
      }
    ],
    "episodeCount": 1
  },
  {
    "slug": "sipi-101",
    "index": 23,
    "kind": "channel",
    "title": "SIPI 101",
    "short": "Signal and power integrity",
    "description": "Signal and power integrity: when a clock edge turns a trace into a transmission line, and what to do about it.",
    "domains": [
      "PCB",
      "EMI/EMC"
    ],
    "level": "Intermediate",
    "image": "/images/series/sipi-101.jpg",
    "topics": [
      {
        "title": "Same 10 MHz clock. Why does the new chip ring?"
      },
      {
        "title": "A 1 ns edge on a 3-inch trace. How much of it fits?"
      }
    ]
  },
  {
    "slug": "interview-round",
    "index": 24,
    "kind": "channel",
    "title": "Interview Round",
    "short": "Four questions a Short",
    "description": "Rapid-fire rounds: four questions per Short on circuits and PCB rules, each answered on screen.",
    "domains": [
      "Electronics",
      "PCB"
    ],
    "level": "Beginner",
    "image": "/images/series/interview-round.jpg",
    "topics": [
      {
        "title": "4 circuit questions every hardware interview asks"
      },
      {
        "title": "4 PCB rules every hardware interview asks"
      }
    ]
  }
];
