import type { Series } from "./types";

/**
 * The eleven learning series. Topic lists are the ones that define each
 * track's scope — they are the syllabus, not decoration, so they are given
 * in full and are what the series page renders.
 *
 * `episodeCount` is omitted where nothing is published yet. An invented
 * count is the fastest way to lose a technical audience.
 */
export const series: Series[] = [
  {
    slug: "electronics-101",
    index: 1,
    title: "Electronics 101",
    short: "Fundamentals, properly",
    description:
      "Electronics from first principles to working intuition. Every result is derived on screen rather than asserted, so the formulas end up meaning something.",
    domains: ["Electronics"],
    level: "Beginner",
    image: "/images/series/electronics-101.jpg",
    topics: [
      { title: "Voltage, Current & Resistance" },
      { title: "Ohm's Law" },
      { title: "Kirchhoff's Laws" },
      { title: "Diodes" },
      { title: "Transistors" },
      { title: "Op-Amps" },
      { title: "Filters" },
      { title: "Amplifiers" },
      { title: "Digital Electronics" },
      { title: "Basic Circuit Analysis" },
    ],
  },
  {
    slug: "rf-101",
    index: 2,
    title: "RF 101",
    short: "Practical RF & microwave",
    description:
      "Why 50 ohms, what a Smith chart is actually for, and how to read S-parameters without guessing. The RF groundwork every other track leans on.",
    domains: ["RF"],
    level: "Intermediate",
    image: "/images/series/rf-101.jpg",
    topics: [
      { title: "RF Fundamentals" },
      { title: "Frequency & Wavelength" },
      { title: "Impedance" },
      { title: "50 Ω Systems" },
      { title: "Transmission Lines" },
      { title: "Smith Chart" },
      { title: "S-Parameters" },
      { title: "VSWR" },
      { title: "Return Loss" },
      { title: "RF Filters" },
      { title: "RF Amplifiers" },
      { title: "Mixers" },
      { title: "Oscillators" },
      { title: "RF Front-End Architecture" },
    ],
  },
  {
    slug: "antenna-101",
    index: 3,
    title: "Antenna 101",
    short: "What actually radiates",
    description:
      "From why a changing current radiates at all, through the half-wave dipole and 73 ohms, to arrays and the array factor. Patterns are computed, never drawn freehand.",
    domains: ["Antenna", "RF"],
    level: "Intermediate",
    image: "/images/series/antenna-101.jpg",
    topics: [
      { title: "Antenna Fundamentals" },
      { title: "Radiation Mechanism" },
      { title: "Gain & Directivity" },
      { title: "Polarization" },
      { title: "Efficiency" },
      { title: "Bandwidth" },
      { title: "Resonance" },
      { title: "Dipole" },
      { title: "Monopole" },
      { title: "Patch Antenna" },
      { title: "Array Antennas" },
      { title: "Feeding Techniques" },
      { title: "Antenna Measurement" },
      { title: "Practical Antenna Design" },
    ],
  },
  {
    slug: "hfss-101",
    index: 4,
    title: "HFSS 101",
    short: "Simulation you can trust",
    description:
      "Hands-on Ansys HFSS, including the parts tutorials skip: what a boundary really does, why your mesh is lying, and how to tell a converged result from a pretty one.",
    domains: ["Simulation", "Antenna", "RF"],
    level: "Intermediate",
    image: "/images/series/hfss-101.jpg",
    topics: [
      { title: "HFSS Interface" },
      { title: "Creating Geometry" },
      { title: "Materials" },
      { title: "Boundaries" },
      { title: "Excitations" },
      { title: "Mesh" },
      { title: "Solution Setup" },
      { title: "S11" },
      { title: "VSWR" },
      { title: "Gain" },
      { title: "Radiation Pattern" },
      { title: "Current Distribution" },
      { title: "Parametric Analysis" },
      { title: "Optimization" },
      { title: "Debugging Simulation Errors" },
    ],
  },
  {
    slug: "ads-101",
    index: 5,
    title: "ADS / RF Simulation 101",
    short: "Circuit-level RF",
    description:
      "Keysight ADS for RF circuit work — matching networks, amplifiers, mixers, and the nonlinear simulations that separate a working design from a hopeful one.",
    domains: ["Simulation", "RF"],
    level: "Advanced",
    image: "/images/series/ads-101.jpg",
    topics: [
      { title: "ADS Interface" },
      { title: "Schematic Design" },
      { title: "Transmission Lines" },
      { title: "S-Parameter Simulation" },
      { title: "Smith Chart" },
      { title: "Matching Networks" },
      { title: "RF Amplifiers" },
      { title: "Mixers" },
      { title: "Harmonic Balance" },
      { title: "Noise Figure" },
      { title: "Stability" },
      { title: "Optimization" },
    ],
  },
  {
    slug: "pcb-101",
    index: 6,
    title: "PCB 101",
    short: "Boards that work first time",
    description:
      "Practical PCB engineering with the numbers attached — stack-ups, controlled impedance, return paths, and which of the rules you were taught are actually true.",
    domains: ["PCB", "Electronics"],
    level: "Intermediate",
    image: "/images/series/pcb-101.jpg",
    topics: [
      { title: "PCB Fundamentals" },
      { title: "Stack-up" },
      { title: "Controlled Impedance" },
      { title: "High-Speed Signals" },
      { title: "RF PCB Layout" },
      { title: "Grounding" },
      { title: "Power Integrity" },
      { title: "Signal Integrity" },
      { title: "Via Design" },
      { title: "Transmission Lines" },
      { title: "Design Rules" },
    ],
  },
  {
    slug: "emi-emc-101",
    index: 7,
    title: "EMI/EMC 101",
    short: "Passing the test, and why",
    description:
      "Electromagnetic compatibility as an engineering problem rather than a checklist — where the emissions come from, what shielding really buys, and how to debug a failed scan.",
    domains: ["EMI/EMC", "PCB"],
    level: "Advanced",
    image: "/images/series/emi-emc-101.jpg",
    topics: [
      { title: "EMI Fundamentals" },
      { title: "EMC Fundamentals" },
      { title: "Conducted Emissions" },
      { title: "Radiated Emissions" },
      { title: "Shielding" },
      { title: "Grounding" },
      { title: "Filtering" },
      { title: "PCB EMI" },
      { title: "Cable EMI" },
      { title: "EMC Testing" },
      { title: "Troubleshooting" },
    ],
  },
  {
    slug: "semiconductor-101",
    index: 8,
    title: "Semiconductor 101",
    short: "From junction to wafer",
    description:
      "Semiconductor and IC technology end to end — the physics of the junction, the MOSFET, and the fabrication steps that turn a wafer into a working die.",
    domains: ["Semiconductor", "Electronics"],
    level: "Intermediate",
    image: "/images/series/semiconductor-101.jpg",
    topics: [
      { title: "Semiconductor Fundamentals" },
      { title: "PN Junction" },
      { title: "MOSFET" },
      { title: "CMOS" },
      { title: "IC Fabrication" },
      { title: "Wafer Processing" },
      { title: "Lithography" },
      { title: "Deposition" },
      { title: "Etching" },
      { title: "Packaging" },
      { title: "RFIC" },
      { title: "MMIC" },
    ],
  },
  {
    slug: "rfic-mmic-101",
    index: 9,
    title: "RFIC / MMIC 101",
    short: "RF on silicon and GaAs",
    description:
      "Integrated RF — LNAs, power amplifiers, mixers, VCOs and PLLs — and the process choices (GaAs, GaN, SiGe, CMOS) that decide what is even possible.",
    domains: ["Semiconductor", "RF"],
    level: "Advanced",
    image: "/images/series/rfic-mmic-101.jpg",
    topics: [
      { title: "RFIC Architecture" },
      { title: "LNA" },
      { title: "PA" },
      { title: "Mixer" },
      { title: "VCO" },
      { title: "PLL" },
      { title: "Matching" },
      { title: "Stability" },
      { title: "Noise" },
      { title: "Linearity" },
      { title: "MMIC Technology" },
      { title: "GaAs" },
      { title: "GaN" },
      { title: "SiGe" },
      { title: "CMOS RF" },
    ],
  },
  {
    slug: "embedded-101",
    index: 10,
    title: "Embedded Hardware 101",
    short: "Hardware-first embedded",
    description:
      "Embedded from the hardware side — buses on a scope, ADC front-ends that actually settle, RF interfaces, and debugging a board that will not enumerate.",
    domains: ["Embedded", "Electronics"],
    level: "Intermediate",
    image: "/images/series/embedded-101.jpg",
    topics: [
      { title: "Microcontrollers" },
      { title: "STM32" },
      { title: "Sensors" },
      { title: "ADC/DAC" },
      { title: "SPI" },
      { title: "I2C" },
      { title: "UART" },
      { title: "CAN" },
      { title: "GPS/GNSS" },
      { title: "RF Interfaces" },
      { title: "Hardware Debugging" },
    ],
  },
  {
    slug: "ai-electronics",
    index: 11,
    title: "AI for Electronics",
    short: "Automation that earns its place",
    description:
      "Where machine learning genuinely helps an electronics engineer — surrogate models for EM simulation, optimisation loops, and the Python to run them.",
    domains: ["AI", "Simulation"],
    level: "Advanced",
    image: "/images/series/ai-electronics.jpg",
    topics: [
      { title: "AI for Circuit Design" },
      { title: "AI for RF Design" },
      { title: "Python for Engineering" },
      { title: "Data Analysis" },
      { title: "Surrogate Models" },
      { title: "EM Simulation Automation" },
      { title: "Optimization" },
      { title: "Machine Learning for Engineering" },
    ],
  },
];

export const getSeries = (slug: string) => series.find((s) => s.slug === slug);

/** The "What We Teach" grid on the home page. */
export const teachingAreas = [
  { label: "Electronics Fundamentals", href: "/series/electronics-101" },
  { label: "RF & Microwave", href: "/series/rf-101" },
  { label: "Antenna Design", href: "/series/antenna-101" },
  { label: "PCB Design", href: "/series/pcb-101" },
  { label: "EMI/EMC", href: "/series/emi-emc-101" },
  { label: "Semiconductor Technology", href: "/series/semiconductor-101" },
  { label: "RFIC & MMIC", href: "/series/rfic-mmic-101" },
  { label: "Simulation & Engineering Tools", href: "/series/hfss-101" },
  { label: "Embedded & Hardware Systems", href: "/series/embedded-101" },
  { label: "AI for Electronics", href: "/series/ai-electronics" },
];
